jwt:
  key:
    access: 7ZmI7Ie87ZWRIO2UhOuhnOygne2KuCBhY2Nlc3MgdG9rZW4= #홈쇼핑 프로젝트 access token
    refresh: 7ZmI7Ie87ZWRIO2UhOuhnOygne2KuCByZWZyZXNoIHRva2Vu #홈쇼핑 프로젝트 refresh token
  max-age:
    access: 1800 #60 *30
    refresh: 604800 #60 * 60 * 24 * 7